### ISSUE TITLE
Confusión uso de programaciones copiadas

### ISSUE THREAD

**Issue by davidmtobias** [jjmartinr01/gauss3#25]
Abro este asunto a raíz del siguiente mensaje:

_"A la hora de realizar las programaciones de 2º, 4º y 6º de primaria algunos de ellos se han basado en las programaciones de los cursos impares. Las han ido realizando correctamente pero llegado el momento de ponerlas como definitiva el sistema les da error ya que refleja que ya una definitiva para ese curso. Sería conveniente revisar este aspecto o bien comunicarlo al principio, ya que, una vez concluida la programación es cuando te das cuenta del problema y para poder solucionarlo supone copiar todo en una nueva."_

**Solución:**
Deberíamos poner algún aviso en las programaciones copiadas para avisar de que esa programación únicamente vale para ESE CURSO y ESA MATERIA

**Duda:**
La copia de las programaciones es útil para copiar programaciones de un año a otro, ¿verdad? Es decir, cuando cambia la Ronda, o incluso la entidad. Pero para una ENTIDAD y un RONDA dada, solo puede existir una programación de un CURSO y MATERIA marcada como DEFINITIVA. ¿Es correcto?

**Comment by rjalamanac** [comment]
Tras la conversación con Juanjo, solo puede haber, dado un curso y una materia, una programación definitiva. Esto implica que si se hacen copias, estas copias no se podrán poner de manera definitiva de manera simultánea. Por lo tanto, no será posible "copiar" la programación como base de un curso para otro.
